name : badass
uuid : 9ff6a484-e482-40e1-ac55-e259a5f58597
description : "Badass is an asset manager SDK."
authors : [Rachid Chikh]
config_version : 0
version : 0.0.1

requires :
- pycouchdb

commands:
- export BADASSVER=0.0.1
- export BADASS=!ROOT!/badass
- export PYTHONPATH=$PYTHONPATH:$BADASS
