name : badass

uuid : 9ff6a484-e482-40e1-ac55-e259a5f58597

description : "Badass is an asset manager."
authors : [Rachid Chikh]
config_version : 0
version : 0.1.0
#variants :
#- [ platform-linux, gcc-4.1.2, boost-1.47.0, python-2.6 ]
#- [ platform-linux, gcc-4.1.2, boost-1.47.0, python-2.7 ]
#requires :
#- pyside
# build_requires:
# - doxygen
commands:
#- export CMAKE_MODULE_PATH<<!ROOT!/cmake
#- export PATH<<!ROOT!/bin
- export PYTHONPATH=$PYTHONPATH:!ROOT!/src
