name : badass
uuid : 9ff6a484-e482-40e1-ac55-e259a5f58597
description : "Badass is an asset manager SDK."
authors : [Rachid Chikh]
config_version : 0
version : 0.0.12

requires :
- couchdb

commands:
- export BD_ASSVER=!VERSION!
- export BD_ASS=!ROOT!
- export PYTHONPATH=$BD_ASS:$PYTHONPATH
